---
title: Machine Learning Final Project
author:
 - Adam Lodrik
 - Favre Stefan
 - Macaraeg Jeff
institute : University of Lausanne
date: today
title-block-banner: "#0095C8" #chosen for the university of lausanne
toc: true
toc-location: right
format: 
  html:
    number-sections: true
    html-math-method: katex
    self-contained: true
    code-fold: true
    code-block-bg: true
    code-block-border-left: "#0095C8"
    code-summary: "Show the code"
    link-external-icon: true
    link-external-newwindow: true
  # pdf: default # use this if you want to render pdfs instead
abstract: |
 Our Machine Learning Final Project is aimed at developing a predictive model capable of identifying the make (i.e. the brand) of a vehicle based on its characteristics, including for example consumption, range, and fuel type. To achieve this, we employed advanced machine learning algorithms, specifically classification trees (CT) and neural networks (NN). Recognizing that certain vehicles might exhibit identical characteristics yet differ across other dimensions, we aimed to create a robust model proficient in accurately predicting a vehicle’s brand from its features. Additionally, we explored the potential of clustering our models using unsupervised learning techniques. This project not only reinforced our understanding of machine learning concepts but also demonstrated their practical applicability in addressing real-world problems.
---

```{r Loading the packages, echo = FALSE, message = FALSE, warning = FALSE}
# loading all the necessary packages
source(here::here("scripts/setup.R"))
```

```{r child = paste0("sections/", c("introduction.qmd","data_description_html.qmd", "EDA_Uncleaned.qmd", "data_cleaning.qmd", "methods.qmd", "results_classification_tree.qmd", "results_neural_network.qmd", "results_unsupervised_learning.qmd", "recommendations_and_discussion.qmd", "references.qmd", "annex.qmd"))}
```